wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    code_path: code/trainval_cap_net.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.20
      8:
      - 5
